### ISSUE TITLE
Rogue copy in the Support page - delete

### ISSUE THREAD

**Issue by paola-roccuzzo** [alphagov/paas-product-page#58]
This line
https://github.com/alphagov/paas-product-page/blob/e5fe1631fa2abdb583af0b24bfbf6c70a1479415/views/support.erb#L121
looks like a remnant of the old Support page and should be deleted.

**Comment by carolinegreen** [comment]
The page has changed slightly since March but the text about not sharing email addresses is still there.  Do we still want to delete it?

https://github.com/alphagov/paas-product-page/blob/eecd5e3c8d626d533cb844a45a2b63a209912b33/views/support.erb#L25

**Comment by paola-roccuzzo** [comment]
No, this issue was fixed with a previous release, I just forgot to close it here.
